language: go

go:
  - 1.11.x
  - 1.12.x
  - 1.13.x

env:
  global:
    - GO111MODULE=on

script: make test

after_success:
  - go get -u github.com/haya14busa/goverage
  - goverage -v -coverprofile=coverage.out ./...
  - go get github.com/schrej/godacov
  - godacov -t $CODACY_TOKEN -r coverage.out -c $TRAVIS_COMMIT